receivers:
  otlp:
    protocols:
      grpc:
      
exporters:
  prometheus:
    endpoint: "${OTL_HOST}:8889"
    const_labels:
      label1: value1

  logging:

  zipkin:
    endpoint: "${ZIPKIN_HOST}:9411/api/v2/spans"
    format: proto

  otlp:
    endpoint: ${JAEGER_HOST}:14250
    tls:
      insecure: true

  elasticsearch:
    endpoints:
    - "http://elastic_search:9200"

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, zipkin, otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, elasticsearch]
